BEGIN;
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m9061$nota-0226$m9061$, $m9062$Ressíntese de glicogênio muscular ocorre a ~5-7%/hora mesmo com ingestão ótima de carboidrato; restauração completa após depleção leva no mínimo 20 horas$m9062$, $m9063$nutricao-e-energia$m9063$,
  $m9064$contexto$m9064$, $m9065$referencia$m9065$,
  ARRAY[$m9066$diario$m9066$, $m9067$semanal$m9067$]::text[], '{}'::text[],
  0.75, $m9068$ativo$m9068$, $m9069$Mesmo em condições ótimas de ingestão de carboidrato pós-exercício, a ressíntese de glicogênio muscular ocorre a uma taxa de apenas **~5-7% por hora**. Isso significa que, após um exercício que depletou significativamente o glicogênio, são necessárias **no mínimo 20 horas** para restaurar completamente as reservas — mesmo com estratégia nutricional ideal.

Estratégia prática citada: consumir 50-75 g de carboidrato de alto a moderado índice glicêmico a cada 2 horas até atingir 500-700 g totais (ou 7-10 g/kg de massa corporal), ou até fazer uma refeição grande rica em carboidrato. Alternativa se a ingestão imediata pós-exercício for impraticável: refeições de 2,5 g de carboidrato de alto índice glicêmico por kg de massa corporal em 2, 4, 6, 8 e 22h pós-exercício, produzindo ressíntese equivalente. Blends de carboidrato incluindo frutose e/ou galactose (além de glicose/maltodextrina) parecem melhorar especificamente a ressíntese de glicogênio hepático. A ressíntese ocorre mais rápido se o atleta permanecer inativo durante a recuperação.

Isso tem uma implicação prática importante: dias consecutivos de treino intenso ("hard days") tendem a depletar progressivamente as reservas de glicogênio hepático e muscular ao longo de vários dias, podendo levar a um estado de "training staleness" (estagnação por depleção crônica), mesmo com boa nutrição — porque a janela de 20h+ para restauração completa frequentemente não cabe entre sessões de treino consecutivas de alto volume.

Aplicação ao feedback: nenhum sinal do Strava mede glicogênio diretamente, mas esta cinética de reposição (20h+ para restauração completa, 5-7%/hora) é um contexto relevante para interpretar por que sessões de alta carga (trabalho-kJ elevado) em dias consecutivos sem folga adequada tendem a produzir queda de desempenho — a causa pode ser depleção de glicogênio ainda não totalmente revertida, e não necessariamente fadiga neuromuscular ou cardiovascular.

**Nota de reconciliação (2026-08-02):** os números "5-7%/hora" e "mínimo 20h" são citação literal da mesma frase-fonte (McArdle p.97) — não é erro de transcrição. A aparente tensão aritmética (100%÷7%/h≈14,3h, não 20h) se resolve porque a ressíntese de glicogênio **não é linear**: pesquisa em fisiologia do exercício confirma um padrão bifásico — uma fase rápida inicial (primeiros 30-60min, independente de insulina, taxa mais alta) seguida de uma fase bem mais lenta (dependente de insulina, o resto do processo). A taxa "5-7%/hora" citada por McArdle descreve essa fase inicial/média, não uma taxa constante ao longo de todo o processo — a fase final mais lenta puxa a média geral pra baixo, o que explica por que o "mínimo 20h" de restauração completa é maior do que a divisão simples sugeriria. Não presumir taxa constante de 5-7%/h ao estimar tempo de restauração parcial em qualquer skill futura.$m9069$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m9070$nota-0227$m9070$, $m9071$Protocolo de monitoramento de hidratação: cada 0,45kg (1 libra) de peso perdido = ~450mL de desidratação; repor líquido a pelo menos 80% da taxa de sudorese durante exercício prolongado$m9071$, $m9072$nutricao-e-energia$m9072$,
  $m9073$contexto$m9073$, $m9074$protocolo$m9074$,
  ARRAY[$m9075$diario$m9075$]::text[], '{}'::text[],
  0.7, $m9076$ativo$m9076$, $m9077$Protocolo prático (McArdle, baseado em recomendações de fisiologia do exercício) para estimar e repor perda hídrica durante exercício prolongado:

1. **Estimar a taxa de desidratação pela variação de peso corporal**: pesar antes e depois do exercício (urinando antes da pesagem pós-exercício, para não distorcer o cálculo). Cada 0,45 kg (1 libra) de peso perdido equivale a aproximadamente **450 mL (15 oz) de líquido perdido**. Essa é a forma mais simples de estimar a taxa de sudorese individual (kg perdidos ÷ horas de exercício = taxa de suor em kg/h ≈ L/h).
2. **Repor líquido durante o exercício a uma taxa próxima de 80% da taxa de sudorese estimada** (repor 100% em tempo real é impraticável devido a limites de esvaziamento gástrico).
3. **Combinar com carboidrato**: bebida de 4-8% de carboidrato, ~625-1250 mL/hora (média de 250 mL a cada 15 minutos), entregando também 30-60 g de carboidrato/hora.

Hipohidratação de até 4% da massa corporal não prejudica a taxa de esvaziamento gástrico, mas perdas maiores tendem a comprometer termorregulação e desempenho cardiovascular. O volume máximo de reposição prático fica perto de 1000 mL/hora — volumes maiores tendem a causar desconforto gastrointestinal.

**Nota de reconciliação (2026-08-02):** este "~1000 mL/hora" não é citação literal da fonte listada em `fontes` (que cobre 450mL/libra, reposição a 80% do suor, e a bebida de carboidrato 625-1250mL/h) — é um teto prático mencionado no corpo sem trecho de apoio direto. nota-0259 (protocolo ACSM, mesma fonte McArdle) cita um teto um pouco mais alto, até 1180 mL/h. Busca externa (ciência do esporte) confirma que a faixa prática de limite de esvaziamento gástrico durante exercício fica em torno de 600-1200 mL/hora, com variação individual — os dois números desta base (1000 e 1180) cabem confortavelmente dentro dessa faixa. Não é uma contradição real: são dois pontos plausíveis do mesmo intervalo aceito, não dois limites concorrentes. Ao comunicar um teto ao atleta, tratar como faixa (~1000-1180 mL/h) em vez de um valor fixo único.

**O que fazer quando a taxa de sudorese estimada excede o teto de reposição fisiológico (2026-08-02, achado de auditoria adversarial):** cruzando com nota-0255 (tabela de sudorese por peso/velocidade/clima), um atleta pesado (ex.: 90kg) pedalando forte no calor pode ter taxa de sudorese prevista de ~1,76 L/h — acima do teto prático de reposição de ~1000-1180 mL/h desta nota e de nota-0259, mesmo repondo a 80% da taxa (regra do passo 2 acima). Nesses casos, o objetivo não pode ser "repor a mesma taxa da perda" (fisiologicamente impossível acima do teto de esvaziamento gástrico) — busca externa (ACSM, diretriz revisada de reposição de fluido) confirma que o objetivo recomendado é diferente: **evitar que a perda acumulada de massa corporal ultrapasse ~2% do peso corporal ao longo da sessão**, não igualar a ingestão à taxa de sudorese em tempo real. Na prática: quando a taxa de sudorese estimada/medida exceder o teto de ~1000-1180 mL/h, repor líquido no teto prático (não tentar forçar mais, risco de desconforto gastrointestinal) e usar a duração da sessão para estimar o déficit acumulado esperado (taxa de sudorese × horas − reposição real); se esse déficit projetado ultrapassar ~2% do peso corporal do atleta, sinalizar risco de comprometimento de termorregulação/desempenho cardiovascular (ver ressalva já existente nesta nota sobre hipohidratação >4%) e considerar reduzir a intensidade/duração planejada da sessão, não apenas "beber mais", que já não é fisiologicamente viável acima do teto.

Aplicação ao feedback: o Strava não registra peso corporal pré/pós-treino nem ingestão de líquido, então este protocolo não pode ser executado automaticamente a partir dos dados de atividade — permanece como conteúdo de referência/educativo que o produto pode sugerir ao atleta como prática a adotar manualmente (pesagem antes/depois de sessões longas e quentes), especialmente relevante quando o Strava mostra sessões de duração longa (tempo-movimento >2-3h) combinadas com temperatura elevada.$m9077$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
COMMIT;