BEGIN;
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m11326$nota-0220$m11326$, $m11327$Treino intervalado de alta intensidade (HIIT) melhora VO2máx mais que treino contínuo moderado (+5,5 vs. +4,9 mL/kg/min vs. controle; HIIT supera moderado em 1,2 mL/kg/min) — meta-análise de ensaios controlados, não estudo único$m11327$, $m11328$tipos-de-treino$m11328$,
  $m11329$direta$m11329$, $m11330$regra-interpretacao$m11330$,
  ARRAY[$m11331$mensal$m11331$]::text[], ARRAY[$m11332$tempo-em-zona$m11332$, $m11333$FC (média/máx)$m11333$]::text[],
  0.7, $m11334$ativo$m11334$, $m11335$**Nota sobre Política de ativação:** esta afirmação NÃO é rebaixada — é baseada numa revisão sistemática com meta-análise de ensaios controlados (Milanović et al. 2015, Sports Medicine), não num estudo isolado, portanto mantém `aplicacao: direta` com confiança mais alta que as notas de estudo único desta fonte.

HIIT (treino intervalado de alta intensidade) produz maior ganho de VO2máx que treino contínuo de intensidade moderada: +5,5 mL/kg/min vs. controle (não-treino) para HIIT, contra +4,9 mL/kg/min para treino moderado — uma vantagem de 1,2 mL/kg/min para HIIT. Fatores que amplificam o efeito do HIIT: repetições mais longas, participantes mais velhos (respondem proporcionalmente mais), intervenções de treino mais longas, maior razão trabalho:descanso, e menor nível de aptidão de base (quem parte de pior forma ganha mais).

**Nota de auditoria (2026-08-02):** os três números acima (5,5 / 4,9 / 1,2) parecem, à primeira vista, inconsistentes por subtração simples (5,5−4,9=0,6≠1,2) — já foi sinalizado como possível erro aritmético em auditoria adversarial. Verificação contra o artigo original (Milanović et al. 2015, PDF completo em research.tees.ac.uk) confirmou que **não é erro**: são três meta-análises separadas, com conjuntos de estudos diferentes — HIT vs. controle (5,5, ±1,2), treino moderado vs. controle (4,9, ±1,4), e a comparação **direta** cabeça a cabeça entre HIT e treino moderado, feita só com os estudos que testaram os dois grupos no mesmo experimento (1,2, ±0,9). Comparação direta e indireta em meta-análise não precisam bater por subtração — usam bases de dados distintas. O valor correto a citar como "vantagem do HIIT sobre o moderado" é 1,2 mL/kg/min, e é o que já está na nota.

Aplicação ao feedback: reforça, com evidência de maior qualidade (meta-análise) que a recomendação já presente no cânone de priorizar sessões intervaladas de alta intensidade para estimular VO2máx (Livro 1, nota-0042; Manual, catálogo de sessões nota-0199) — o produto pode usar esse achado para justificar por que recomenda intervalados em vez de apenas mais volume em Zona 2 quando o objetivo declarado é aumentar VO2máx/potência aeróbia máxima, especialmente para atletas mais velhos ou com aptidão de base mais baixa (que tendem a responder ainda melhor).$m11335$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m11336$nota-0221$m11336$, $m11337$Protocolo 4×4min a 90-95% FCmáx (3min recuperação ativa a 70% FCmáx) aumenta VO2máx em 8,8% em 8 semanas — mais que 15on/15off (+6,4%), e muito mais que corrida contínua a 70% FCmáx (+1,8% NS) ou no limiar de lactato (+2,0% NS), com mesmo gasto energético total (Helgerud et al. 2007)$m11337$, $m11338$tipos-de-treino$m11338$,
  $m11339$direta$m11339$, $m11340$protocolo$m11340$,
  ARRAY[$m11341$mensal$m11341$]::text[], ARRAY[$m11342$tempo-em-zona$m11342$, $m11343$FC (média/máx)$m11343$, $m11344$potência-por-lap$m11344$]::text[],
  0.7, $m11345$ativo$m11345$, $m11346$**Nota sobre Política de ativação:** estudo controlado clássico (Helgerud et al. 2007), amplamente replicado e citado na literatura (o "protocolo 4×4 norueguês"), com desenho comparativo controlado (4 grupos, mesmo gasto energético total) — mantido em `aplicacao: direta` com confiança relativamente alta, mas registrado como um único estudo original (não meta-análise) para transparência.

Comparação direta de 4 protocolos de treino (3x/semana, 8 semanas, todos igualados por consumo total de oxigênio/gasto energético): corrida contínua a 70% FCmáx por 45min (+1,8% VO2máx, não significativo); corrida contínua no limiar de lactato/85% FCmáx por ~25min (+2,0%, não significativo); 15s trabalho a 90-95% FCmáx / 15s recuperação ativa a 70% FCmáx, 45 repetições (+6,4%); **4 séries de 4 minutos a 90-95% FCmáx, com 3 minutos de recuperação ativa a 70% FCmáx entre elas (+8,8%, o melhor resultado)**. Ambos os protocolos intervalados também aumentaram o volume sistólico máximo (mecanismo central, ver nota-0157/nota-0210), provável razão principal do maior ganho de VO2máx. Conclusão dos autores: treino intervalado de alta intensidade aeróbia é significativamente mais eficaz que o mesmo volume total de trabalho feito no limiar de lactato ou a 70% da FCmáx.

Aplicação ao feedback: fornece um protocolo específico, com FC-alvo claramente definida (90-95% FCmáx trabalho / 70% FCmáx recuperação) e evidência comparativa robusta — o produto pode usar este protocolo como referência de "padrão-ouro" ao reconhecer ou recomendar sessões de VO2máx do tipo 4×4min no histórico do Strava (via tempo-em-zona/potência-por-lap cruzado com FC), e comunicar ao usuário por que esse formato específico tende a ser mais eficaz que sessões contínuas de limiar ou endurance para o objetivo de elevar VO2máx.$m11346$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m11347$nota-0222$m11347$, $m11348$O volume total da sessão de HIIT (duração × repetições) é o principal preditor de ganho de VO2máx, mais do que a duração específica do intervalo — intervalos curtos precisam de muitas repetições; intervalos longos precisam de menos; o que importa é o tempo total em % alto de FC/VO2máx (meta-análise Wen et al. 2019, N=1.514)$m11348$, $m11349$tipos-de-treino$m11349$,
  $m11350$direta$m11350$, $m11351$regra-interpretacao$m11351$,
  ARRAY[$m11352$diario$m11352$, $m11353$semanal$m11353$]::text[], ARRAY[$m11354$tempo-em-zona$m11354$, $m11355$potência-por-lap$m11355$, $m11356$FC (média/máx)$m11356$]::text[],
  0.68, $m11357$ativo$m11357$, $m11358$**Nota sobre Política de ativação:** meta-análise de 1.514 participantes (Wen et al. 2019) — evidência de alta qualidade, mantida em `aplicacao: direta`.

Classificação de HIIT por duração de intervalo (longo >2min, moderado 30s-2min, curto 10-30s, sprint <10s) e por volume total da sessão (alto >15min de trabalho acumulado, moderado 5-10min, baixo <5min). Principal achado: **o volume total de trabalho em alta intensidade acumulado na sessão é o maior preditor de ganho de VO2máx** — mais importante que a duração específica de cada intervalo. Intervalos longos (>2min) e volume alto (>15min) tendem a ser mais eficazes que intervenções curtas/baixo volume, mas todos os formatos de HIIT (mesmo sprints <10s com <5min de volume total e <4 semanas de duração) produziram alguma melhora de VO2máx. Regra prática de intensidade: intervalos curtos/sprint precisam ser verdadeiramente "all-out" (esforço máximo); intervalos mais longos podem ser submáximos, mas ainda muito difíceis.

Aplicação ao feedback: reforça que o produto não deveria tratar apenas "quantos minutos em Zona 5" como métrica secundária — o **volume acumulado de tempo em alta intensidade dentro de uma sessão** (soma de todas as repetições, não só a duração de uma repetição isolada) é o sinal mais preditivo de estímulo de VO2máx. Ao avaliar se uma sessão intervalada "valeu a pena" para o objetivo de VO2máx, o produto deveria somar o tempo total em zona alta (via tempo-em-zona/potência-por-lap) em vez de avaliar apenas a duração individual dos intervalos prescritos — e verificar se intervalos curtos foram de fato executados em intensidade máxima (não apenas "forte").$m11358$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
COMMIT;