BEGIN;
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m9936$nota-0195$m9936$, $m9937$Fadiga periférica (músculo: glicogênio, cálcio, fosfato inorgânico) vs. fadiga central (SNC: comando motor, neurotransmissores, percepção de esforço) — em provas muito longas a fadiga central ganha importância crescente$m9937$, $m9938$recuperacao-e-fadiga$m9938$,
  $m9939$contexto$m9939$, $m9940$conceito$m9940$,
  ARRAY[$m9941$diario$m9941$]::text[], '{}'::text[],
  0.55, $m9942$ativo$m9942$, $m9943$Distinção clássica de dois mecanismos de fadiga: (1) Fadiga periférica — ocorre no próprio músculo (redução de glicogênio, alterações de cálcio intracelular, acúmulo de fosfato inorgânico, alterações iônicas, redução da capacidade contrátil); (2) Fadiga central — ocorre no sistema nervoso central (alterações de neurotransmissores, aumento da percepção de esforço, mecanismos protetores cerebrais, fadiga mental), manifestando-se como redução do comando motor enviado aos músculos. Em provas extremamente longas (ultraciclismo, provas de muitas horas), a fadiga central assume importância crescente relativa à periférica.

Aplicação ao feedback: nota de contexto mecanístico — não gera regra de interpretação direta de dado do Strava (não há como diferenciar fadiga central de periférica a partir de potência/FC isoladamente), mas explica por que a queda de potência em provas muito longas pode não refletir esgotamento puramente muscular/metabólico, sendo relevante para moderar a linguagem de feedback em sessões ultra-longas.$m9943$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m9944$nota-0196$m9944$, $m9945$Supercompensação: fadiga → recuperação → desempenho temporariamente acima do nível inicial → novo estímulo nesse momento gera evolução — mas cada capacidade (glicogênio, força, capacidade aeróbia, SNC, tecido conjuntivo) tem tempo de recuperação próprio, não existe curva única$m9945$, $m9946$recuperacao-e-fadiga$m9946$,
  $m9947$contexto$m9947$, $m9948$conceito$m9948$,
  ARRAY[$m9949$semanal$m9949$]::text[], '{}'::text[],
  0.55, $m9950$ativo$m9950$, $m9951$Modelo clássico de supercompensação: um estímulo de treino adequado gera fadiga (queda temporária de capacidade), seguida de recuperação, que pode elevar o desempenho temporariamente acima do nível pré-treino (supercompensação) — se um novo estímulo for aplicado nessa janela, ocorre evolução progressiva; se aplicado cedo demais (sem recuperação) ou tarde demais (após a supercompensação decair), o ganho é subótimo. Ressalva importante do Manual: não existe uma curva única de supercompensação — glicogênio muscular, força máxima, capacidade aeróbia, sistema nervoso e tecido conjuntivo recuperam-se em velocidades diferentes, exigindo que o planejamento considere múltiplas linhas do tempo simultâneas, não uma única "janela ótima".

Aplicação ao feedback: fundamenta teoricamente a lógica de TSB (Training Stress Balance) já operacionalizada no Livro 1 como proxy prático de "forma"/supercompensação — reforça a cautela de que um TSB positivo (indicando recuperação/forma) não significa que todas as capacidades do atleta estão igualmente recuperadas; a supercompensação de capacidade aeróbia pode não coincidir com a de força/neuromuscular.$m9951$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m9952$nota-0197$m9952$, $m9953$VFC (Variabilidade da Frequência Cardíaca): estimativa indireta do sistema nervoso autônomo; valores baixos podem indicar fadiga/estresse/recuperação incompleta — alta variabilidade individual exige interpretar tendência ao longo do tempo, não valor isolado$m9953$, $m9954$recuperacao-e-fadiga$m9954$,
  $m9955$contexto$m9955$, $m9956$conceito$m9956$,
  ARRAY[$m9957$diario$m9957$, $m9958$semanal$m9958$]::text[], '{}'::text[],
  0.5, $m9959$ativo$m9959$, $m9960$VFC (Variabilidade da Frequência Cardíaca / HRV) estima indiretamente a atividade do sistema nervoso autônomo. Valores reduzidos em relação à linha de base do próprio atleta podem sinalizar fadiga, estresse ou recuperação incompleta — mas a VFC tem grande variabilidade individual e intra-individual (dia a dia), então valores absolutos isolados são pouco informativos; o que importa é a tendência ao longo do tempo (média móvel/desvio da linha de base pessoal).

Aplicação ao feedback: **Política de ativação aplicada** — VFC não é um sinal nativo do Strava (é medido por wearables/apps dedicados como HRV4Training, Whoop, Garmin, etc.); permanece `aplicacao: contexto` por depender de dado externo não incluído no glossário de sinais do produto. Só se tornaria operacionalizável (`aplicacao: direta`) se o produto passasse a receber esse dado via integração explícita — nesse caso, a nota já registra a cautela essencial (comparar contra linha de base individual, não valor absoluto).$m9960$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m9961$nota-0198$m9961$, $m9962$Fadiga acumulada deve ser inferida cruzando múltiplos sinais simultaneamente (potência reduzida + FC elevada + RPE alta + sono ruim + VFC reduzida), nunca a partir de uma única variável isolada$m9962$, $m9963$recuperacao-e-fadiga$m9963$,
  $m9964$direta$m9964$, $m9965$regra-interpretacao$m9965$,
  ARRAY[$m9966$diario$m9966$, $m9967$semanal$m9967$]::text[], ARRAY[$m9968$potência-média$m9968$, $m9969$FC (média/máx)$m9969$, $m9970$esforço-relativo (Relative Effort)$m9970$]::text[],
  0.55, $m9971$ativo$m9971$, $m9972$Princípio central de interpretação: fadiga acumulada não deve ser inferida a partir de uma única variável (ex.: só a queda de potência, ou só o aumento de FC), pois cada sinal isolado tem múltiplas explicações possíveis. O exemplo do Manual: potência reduzida + FC elevada para a mesma potência + RPE alto + sono ruim + VFC reduzida, combinados, sugerem fadiga acumulada com muito mais confiança do que qualquer um desses sinais isoladamente.

Aplicação ao feedback: dos sinais citados, o produto tem acesso direto via Strava a potência, FC e esforço-relativo (proxy de RPE); qualidade de sono e VFC dependem de integração externa (fora do escopo atual). Regra prática: ao construir um detector de "fadiga acumulada" ou "risco de overreaching", o produto deveria exigir concordância de pelo menos 2 sinais disponíveis (ex.: queda de potência sustentável junto com decoupling Pw:Hr elevado, ou TSB muito negativo junto com esforço-relativo desproporcionalmente alto) em vez de disparar alerta com base em um único sinal isolado — reduz falsos positivos causados por fatores de confusão já registrados (nota-0158, nota-0191).$m9972$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
COMMIT;