BEGIN;
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m3533$nota-0277$m3533$, $m3534$Manutenção da massa óssea exige carga mecânica/gravitacional: em microgravidade (desuso extremo), perda óssea chega a 1%/mês mesmo com treino de força — mecanismo relevante para esportes de baixo impacto como o ciclismo$m3534$, $m3535$fisiologia$m3535$,
  $m3536$contexto$m3536$, $m3537$conceito$m3537$,
  ARRAY[$m3538$mensal$m3538$]::text[], '{}'::text[],
  0.6, $m3539$revisar$m3539$, $m3540$O McArdle, no capítulo sobre microgravidade (voo espacial), documenta com clareza o mecanismo pelo qual a massa óssea depende de **carga mecânica/gravitacional contínua** para se manter: em ambiente de microgravidade (ausência quase total de carga sobre os ossos de sustentação de peso), astronautas perdem massa óssea a uma taxa de **~1% ao mês** nos sítios de sustentação de peso (coluna, colo do fêmur, trocanter, pelve) — a maior preocupação biomédica da NASA para missões espaciais.

O mecanismo bioquímico descrito: sob gravidade normal, a carga mecânica estimula a absorção de cálcio pelo osso, poupando a perda geral de cálcio do corpo. Em microgravidade, a ausência dessa carga reduz a absorção intestinal de cálcio, aumenta a perda fecal, e desregula a reabsorção óssea — resultando em balanço de cálcio negativo e perda progressiva de massa óssea.

**Achado crítico para este canône**: o treinamento de força a bordo (exercício resistido, multimodal, incluindo membros inferiores) **não preveniu a perda de DMO**, apesar do compromisso de tripulações americanas e soviéticas com regimes intensos e diários de treino de resistência muscular. Isso indica que treino de força por si só, sem o componente específico de **impacto/carga axial gravitacional real**, é insuficiente para estimular a manutenção óssea nesse contexto de desuso extremo.

**Relevância inferida para ciclismo** (extrapolação do mecanismo, não afirmação direta do texto sobre ciclismo): o ciclismo é uma atividade de sustentação parcial do peso corporal, sem impacto repetitivo (diferente de corrida, saltos ou esportes de contato), e realizada em posição sentada com boa parte do peso suportado pelo selim/pedais/guidão em vez dos ossos de sustentação. O mesmo princípio geral demonstrado no desuso extremo da microgravidade (mecânica de carga insuficiente → menor estímulo osteogênico → risco de menor densidade óssea) é consistente com a associação, bem descrita na literatura esportiva geral (fora deste texto-fonte), entre ciclismo de alto volume e menor densidade mineral óssea em comparação com esportes de impacto. Esta nota registra o **mecanismo fisiológico geral** (carga mecânica é necessária para manutenção óssea) com base direta na fonte; a extrapolação específica para ciclistas é uma aplicação analógica, não um dado direto do McArdle sobre ciclismo.

Aplicação ao feedback: como o Strava não mede densidade óssea, esta nota não gera regra automática — mas fundamenta uma recomendação educativa relevante: ciclistas de alto volume (`tempo-movimento`/`distância` semanal elevados) que fazem pouco ou nenhum treino complementar de impacto (corrida, saltos) ou musculação com carga axial (agachamento, levantamento terra) podem estar sob risco elevado de menor densidade óssea ao longo do tempo, e o produto pode sugerir a inclusão de treino complementar de impacto/força como medida preventiva — mesmo sabendo que o Strava não pode confirmar ou monitorar diretamente esse risco.$m3540$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m3541$nota-0284$m3541$, $m3542$Prova por etapas de 3 semanas (Giro d'Italia) eleva marcadores de reabsorção óssea em ciclistas profissionais — dado direto em ciclistas, não extrapolação$m3542$, $m3543$fisiologia$m3543$,
  $m3544$contexto$m3544$, $m3545$conceito$m3545$,
  ARRAY[$m3546$mensal$m3546$]::text[], '{}'::text[],
  0.6, $m3547$revisar$m3547$, $m3548$Em um estudo com **nove ciclistas profissionais** que participaram do Giro d'Italia (prova por etapas de 3 semanas), marcadores bioquímicos de atividade óssea foram medidos 1 dia antes da prova, e novamente no 12º e 22º dias de competição. Os marcadores indicaram **reabsorção óssea líquida induzida pela prova** — ou seja, ao longo das 3 semanas de competição intensa, o balanço ósseo dos ciclistas pendeu para perda, não formação.

Este é um dado **direto sobre ciclistas profissionais em competição real** (diferente da nota-0277, que estabelece o mesmo mecanismo geral — carga mecânica/gravitacional insuficiente prejudica a manutenção óssea — a partir de dados de astronautas em microgravidade e o aplica ao ciclismo por analogia). Aqui a fonte já traz o dado específico do esporte, reforçando de forma direta que o ciclismo de alto volume/intensidade, mesmo sem o componente de desuso extremo da microgravidade, ainda produz um ambiente hormonal/metabólico (possivelmente ligado a déficit energético agudo e alto volume de treino, mais do que apenas à ausência de impacto) desfavorável à manutenção óssea durante blocos de carga muito alta.

Nota de confiança: o estudo tem amostra pequena (n=9) e não detalha se a causa é o baixo impacto mecânico, o déficit energético agudo da prova, ou ambos — por isso fica marcada para revisão, mas o achado é consistente com a literatura mais ampla sobre menor densidade mineral óssea em ciclistas de alto volume.

Aplicação ao feedback: reforça, com dado específico do esporte, a recomendação de que ciclistas em blocos de treino/competição de volume muito alto e prolongado (ex.: semanas consecutivas de grande carga, sem descanso) considerem monitorar saúde óssea e complementar com treino de impacto/força axial fora da temporada mais intensa.$m3548$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
COMMIT;