BEGIN;
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m4678$nota-0149$m4678$, $m4679$As quatro perguntas do treinador: framework de decisão para toda prescrição de treino$m4679$, $m4680$metodologia-e-periodizacao$m4680$,
  $m4681$contexto$m4681$, $m4682$conceito$m4682$,
  ARRAY[$m4683$mensal$m4683$]::text[], '{}'::text[],
  0.6, $m4684$ativo$m4684$, $m4685$O Manual propõe que toda decisão de treinamento pode ser reduzida a uma sequência de 4 perguntas: (1) o que limita a performance deste atleta especificamente; (2) como essa limitação pode ser medida; (3) qual adaptação fisiológica precisa ser desenvolvida para superá-la; (4) qual estratégia de treino tem maior probabilidade de produzir essa adaptação. O capítulo também enfatiza uma visão sistêmica da performance: nenhum determinante (fisiológico, biomecânico, psicológico, técnico-tático, ambiental, equipamento) atua isoladamente, e otimizar uma variável isoladamente pode prejudicar outra.

**Nota de transparência (2026-08-02, achado de auditoria adversarial):** o exemplo acima ("reduzir massa corporal favorece relação potência/peso mas pode comprometer recuperação se excessivo") é uma ilustração minha do princípio de "visão sistêmica" do parágrafo anterior, não um exemplo literal do trecho-fonte citado no frontmatter — o trecho-fonte cobre apenas as 4 perguntas, não esse caso específico. Mantido por ser uma ilustração fisiologicamente correta e consistente com o princípio geral do capítulo (não é fato novo inventado, é aplicação do princípio já citado), mas sinalizado aqui para rastreabilidade — esta nota é `aplicacao: contexto` e não gera regra de cálculo direta, então o risco de propagação incorreta é baixo.

Aplicação ao feedback: nota de contexto/framework, não gera regra de interpretação direta de dados Strava. Serve como lente organizadora para o produto — ao identificar uma limitação (ex.: via detectores de fadiga, TSB, distribuição de zonas), o feedback deveria idealmente seguir essa cadeia lógica (limitação → métrica → adaptação-alvo → recomendação), em vez de dar dicas desconectadas do diagnóstico.$m4685$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m4686$nota-0178$m4686$, $m4687$Modelo de quatro domínios de intensidade fisiológica (Moderado / Pesado / Severo / Extremo), delimitados por LT1 e LT2 — modelo alternativo aos sete níveis de Coggan do Livro 1$m4687$, $m4688$metodologia-e-periodizacao$m4688$,
  $m4689$contexto$m4689$, $m4690$conceito$m4690$,
  ARRAY[$m4691$diario$m4691$, $m4692$semanal$m4692$]::text[], '{}'::text[],
  0.55, $m4693$ativo$m4693$, $m4694$O Manual propõe um modelo fisiológico de 4 domínios de intensidade, delimitados pelos limiares LT1 e LT2 (nota-0171, nota-0172): Moderado (abaixo do LT1 — homeostase mantida, predomínio de gordura, baixa fadiga, sustentável por horas); Pesado (entre LT1 e LT2 — estado relativamente estável, maior uso de carboidrato, sustentável por longo período); Severo (acima do LT2 — sem estado estável, VO2 continua subindo, fadiga inevitável em minutos); Extremo (intensidades máximas — predomínio anaeróbio, sustentação muito curta). Esse modelo de 4 domínios é academicamente mais simples e fisiologicamente mais direto que os 7 níveis práticos de Coggan (%FTP/%FTHR) usados no Livro 1 (nota-0022) — ambos descrevem a mesma realidade fisiológica contínua, mas com número de categorias e critérios de corte diferentes (limiares de lactato vs. percentual de FTP). Não são contraditórios, mas não há um mapeamento 1:1 exato entre eles (ex.: o domínio "Pesado" do Manual abrange aproximadamente os Níveis 2-3-parte do 4 de Coggan).

Aplicação ao feedback: registrar como referência conceitual complementar — o produto deve manter os 7 níveis de Coggan (nota-0022) como sistema operacional primário (por ser diretamente calculável a partir de %FTP, já derivável do Strava), mas pode usar a linguagem dos domínios fisiológicos (moderado/pesado/severo/extremo) em explicações educativas para o usuário, já que é mais intuitiva. Par de modelos concorrentes registrado em `_revisao/modelos-concorrentes/` para decisão consciente de qual usar como padrão operacional.$m4694$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m4695$nota-0184$m4695$, $m4696$Modelo de três zonas de Seiler (base do treinamento polarizado): Zona 1 <LT1, Zona 2 entre LT1-LT2, Zona 3 >LT2 — usado na maioria das pesquisas sobre distribuição polarizada de intensidade$m4696$, $m4697$metodologia-e-periodizacao$m4697$,
  $m4698$contexto$m4698$, $m4699$conceito$m4699$,
  ARRAY[$m4700$semanal$m4700$, $m4701$mensal$m4701$]::text[], '{}'::text[],
  0.55, $m4702$ativo$m4702$, $m4703$Stephen Seiler propôs um modelo simplificado de apenas 3 zonas, base da maior parte das pesquisas sobre distribuição polarizada de intensidade: Zona 1 (abaixo do LT1), Zona 2 (entre LT1 e LT2), Zona 3 (acima do LT2). É essencialmente equivalente aos domínios Moderado/Pesado/Severo já registrados na nota-0178 (sem o domínio Extremo separado). O Manual também confirma explicitamente que o modelo de Coggan usado no Livro 1 (nota-0022) é "um dos mais utilizados no ciclismo" — ou seja, não há conflito entre as fontes quanto ao modelo de 7 zonas, apenas a adição deste modelo alternativo mais simples usado especificamente na literatura de polarização.

Aplicação ao feedback: se o produto algum dia implementar lógica de "distribuição polarizada de intensidade" (ex.: razão 80/20 entre volume em baixa e alta intensidade), o modelo de 3 zonas de Seiler é a referência padrão da literatura para essa classificação — mapeável a partir de %FTP usando aproximadamente Zona 1 = Níveis 1-2 de Coggan, Zona 2 = Níveis 3-4, Zona 3 = Níveis 5-7 (aproximação, sem correspondência exata publicada).$m4703$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m4704$nota-0186$m4704$, $m4705$Cinco princípios da adaptação ao treinamento: sobrecarga, especificidade, progressão, reversibilidade, individualidade$m4705$, $m4706$metodologia-e-periodizacao$m4706$,
  $m4707$contexto$m4707$, $m4708$conceito$m4708$,
  ARRAY[$m4709$semanal$m4709$, $m4710$mensal$m4710$]::text[], '{}'::text[],
  0.55, $m4711$ativo$m4711$, $m4712$Cinco princípios fisiológicos que regem qualquer método de treinamento: (1) Sobrecarga — o estímulo precisa perturbar a homeostase o suficiente para gerar adaptação, mas excesso aumenta risco de overreaching; (2) Especificidade — o organismo se adapta exatamente ao estímulo recebido (treino de potência máxima ≠ treino de endurance); (3) Progressão — estímulos precisam aumentar (volume, intensidade, frequência ou complexidade) à medida que o atleta se adapta; (4) Reversibilidade — adaptações regridem quando o treino é interrompido, em velocidades diferentes por capacidade; (5) Individualidade — a mesma sessão produz respostas diferentes em atletas diferentes.

Aplicação ao feedback: framework de referência geral (SAID/FITT) — não gera regra de interpretação direta de um dado isolado do Strava, mas justifica por que o feedback do produto deveria considerar histórico/progressão do atleta (não comparar sessões isoladas sem contexto) e por que perda de forma após períodos sem treino (detectável via queda de CTL/TSB, já no cânone do Livro 1) é esperada e não anômala.$m4712$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
COMMIT;