BEGIN;
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m1776$nota-0164$m1776$, $m1777$VO2máx alto não garante melhor desempenho: atleta com VO2máx menor mas maior economia/FTP pode superar atleta com VO2máx maior — desempenho depende da interação entre VO2máx, limiares, economia, capacidade anaeróbia, durabilidade e estratégia$m1777$, $m1778$contexto-atleta$m1778$,
  $m1779$contexto$m1779$, $m1780$conceito$m1780$,
  ARRAY[$m1781$mensal$m1781$]::text[], '{}'::text[],
  0.55, $m1782$ativo$m1782$, $m1783$Exemplo didático do Manual: Atleta A tem VO2máx de 82 mL·kg⁻¹·min⁻¹ mas FTP de apenas 300W (baixa economia); Atleta B tem VO2máx menor (74) mas FTP maior (340W) e maior resistência à fadiga — o Manual conclui que o Atleta B provavelmente venceria uma prova de estrada. O desempenho depende da interação entre VO2máx, limiares fisiológicos, economia de movimento, capacidade anaeróbia, durabilidade, estratégia e fatores psicológicos — nenhum fator isolado prevê o resultado.

Aplicação ao feedback: reforça um princípio já presente implicitamente no cânone (Livro 1 prioriza FTP/potência-por-peso como métricas práticas derivadas do Strava, em vez de VO2máx laboratorial) — o produto deve evitar qualquer comparação ou ranking de atletas baseado unicamente em capacidade aeróbia máxima; a FTP e a curva de potência-duração (já cobertas pelo Livro 1) são proxies mais completas e diretamente derivadas de dados do Strava.$m1783$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m1784$nota-0200$m1784$, $m1785$Arquétipos de perfil fisiológico por especialidade: Escalador (potência/peso), Contrarrelogista (potência absoluta/aerodinâmica), Velocista (potência neuromuscular/anaeróbia), Clássicas (durabilidade+recuperação repetida), MTB (VO2máx+técnica+recuperação), Ultraciclista (economia+eficiência de gordura)$m1785$, $m1786$contexto-atleta$m1786$,
  $m1787$contexto$m1787$, $m1788$conceito$m1788$,
  ARRAY[$m1789$mensal$m1789$]::text[], '{}'::text[],
  0.5, $m1790$ativo$m1790$, $m1791$O Manual descreve 6 arquétipos de perfil fisiológico associados a especialidades do ciclismo: Escalador (alta relação potência/peso, baixo %gordura, boa economia — potência relativa é o que importa, pequenos ganhos de peso prejudicam desempenho); Contrarrelogista (potência absoluta mais importante que relativa, estabilidade fisiológica, aerodinâmica/posição decisivas); Velocista (potência neuromuscular, capacidade anaeróbia, força máxima, ativação muscular rápida); Especialista em clássicas (combina resistência aeróbia + durabilidade + potência anaeróbia + recuperação entre esforços repetidos — considerado um dos perfis mais completos); Mountain biker (VO2máx elevado, capacidade anaeróbia, recuperação rápida entre picos, técnica com peso maior que na estrada); Ultraciclista (resistência aeróbia excepcional, durabilidade, eficiência de utilização de gordura, estabilidade psicológica). Não existe perfil "ideal" universal — cada modalidade/estratégia de vitória exige uma combinação diferente, e o treinador não deve comparar indiscriminadamente atletas com perfis distintos.

Aplicação ao feedback: complementa o Mapa Fenotípico quantitativo do Livro 1 (nota-0082, baseado em Pmax/FTP/FRC derivados da curva de potência) com uma camada de linguagem narrativa — o produto pode usar esses arquétipos para comunicar ao usuário, de forma mais acessível, o que seu perfil de potência (curva MMP) sugere sobre suas forças/fraquezas relativas ("seu perfil se assemelha mais a um escalador", etc.), desde que a classificação subjacente continue baseada nos dados quantitativos já derivados do Strava (curva potência-duração, relação potência/peso).$m1791$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m1792$nota-0207$m1792$, $m1793$VO2máx aumenta até ~30 anos e depois declina de forma aproximadamente linear, mesmo em atletas treinados/ativos — quanto maior o baseline construído na juventude, maior a 'vantagem' ao longo do declínio$m1793$, $m1794$contexto-atleta$m1794$,
  $m1795$contexto$m1795$, $m1796$conceito$m1796$,
  ARRAY[$m1797$mensal$m1797$]::text[], '{}'::text[],
  0.55, $m1798$ativo$m1798$, $m1799$Segundo a fonte, VO2máx pode aumentar consideravelmente até ~30 anos (em pessoas fisicamente ativas), depois entra em declínio aproximadamente linear a partir dos 30-40 anos — declínio esse observado mesmo em adultos que continuam treinados/ativos (não é exclusivo de sedentários). O ponto prático: quanto maior o VO2máx construído durante a juventude, maior o "baseline" a partir do qual o declínio começa, dando uma vantagem relativa ao longo da vida (ver gráfico comparativo endurance-trained vs. sedentary, mostrando maior aptidão aeróbia em qualquer idade para o grupo treinado).

Aplicação ao feedback: complementa a nota-0036 do Livro 1 (limitações do Power Profile por idade) — reforça que quedas de FTP/potência relacionadas à idade não são necessariamente sinal de destreinamento, mas parte de um processo fisiológico esperado; o produto deveria calibrar expectativas de progresso/retenção de forma por faixa etária, especialmente para atletas master.$m1799$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m1800$nota-0208$m1800$, $m1801$FC máxima declina ~1 bpm/ano; volume sistólico e VO2máx declinam com a idade por rigidez cardíaca, menor resposta autonômica e queda de densidade capilar/mitocondrial$m1801$, $m1802$contexto-atleta$m1802$,
  $m1803$contexto$m1803$, $m1804$conceito$m1804$,
  ARRAY[$m1805$mensal$m1805$]::text[], '{}'::text[],
  0.55, $m1806$ativo$m1806$, $m1807$Detalha os mecanismos fisiológicos por trás do declínio de VO2máx com a idade, organizados pela Equação de Fick (já definida na nota-0162): (1) débito cardíaco cai por queda de FC máxima (~1 batimento/ano, por menor responsividade do sistema nervoso autônomo e rigidez estrutural do coração) e de volume sistólico (coração mais rígido/fraco ejeta e enche menos sangue por batimento); (2) diferença arteriovenosa de O2 cai por menor densidade capilar e menor quantidade/qualidade mitocondrial, reduzindo a extração muscular de oxigênio; soma-se a perda de massa muscular esquelética relacionada à idade.

Aplicação ao feedback: referência de contexto fisiológico para calibrar expectativas de FC máxima/FTP em atletas mais velhos — se o produto usar uma estimativa de FC máxima por idade (ex.: 220-idade ou similar), esta nota fundamenta por que ela declina de forma relativamente previsível (~1bpm/ano); não gera regra de interpretação direta de sessão, mas é relevante para normalizar comparações de desempenho entre atletas de idades diferentes.$m1807$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
COMMIT;