BEGIN;
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m2936$nota-0165$m2936$, $m2937$VO2máx aumenta via adaptações centrais (débito cardíaco) e periféricas (mitocôndrias/capilarização); ganhos diminuem com o nível do atleta (>20% em iniciantes vs. 2-3% em elite)$m2937$, $m2938$fisiologia$m2938$,
  $m2939$contexto$m2939$, $m2940$conceito$m2940$,
  ARRAY[$m2941$mensal$m2941$]::text[], '{}'::text[],
  0.55, $m2942$ativo$m2942$, $m2943$O VO2máx é elevado por treinamento através de adaptações centrais (aumento de volume sistólico, débito cardíaco, volume plasmático — estimuladas principalmente por intervalados de alta intensidade) e periféricas (densidade mitocondrial, atividade enzimática oxidativa, capilarização — estimuladas por volume aeróbio consistente ao longo de anos). O potencial de ganho não é indefinido: iniciantes podem ganhar >20% de VO2máx; atletas de elite tipicamente apenas 2-3%. Consequência prática: em atletas avançados, o foco de treinamento tende a se deslocar do aumento do VO2máx (teto próximo do limite genético/adaptativo) para melhoria de economia de movimento, limiares fisiológicos e durabilidade.

Aplicação ao feedback: reforça a lógica de que o nível/histórico de treinamento do atleta (contexto-atleta) deveria influenciar a priorização de foco no feedback — para atletas iniciantes/intermediários, estímulos de VO2max (intervalados de alta intensidade) tendem a produzir ganhos mais expressivos; para atletas muito treinados, o produto deveria dar mais peso a sinais relacionados a economia/eficiência e resistência à fadiga em vez de insistir unicamente em mais intervalados de VO2max.$m2943$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m2944$nota-0179$m2944$, $m2945$Economia (custo de O2 para uma potência) ≠ Eficiência mecânica (Trabalho ÷ Energia metabólica) — eficiência mecânica no ciclismo é ~20-25%$m2945$, $m2946$fisiologia$m2946$,
  $m2947$contexto$m2947$, $m2948$conceito$m2948$,
  ARRAY[$m2949$mensal$m2949$]::text[], '{}'::text[],
  0.55, $m2950$ativo$m2950$, $m2951$Dois conceitos frequentemente confundidos: Economia (custo energético/VO2 para sustentar uma potência específica — dois atletas na mesma potência podem ter VO2 diferentes, o de menor VO2 tem melhor economia) e Eficiência Mecânica (fração da energia metabólica total convertida em trabalho mecânico útil = Trabalho ÷ Energia Metabólica). No ciclismo, a eficiência mecânica bruta gira em torno de 20-25% — a maior parte da energia produzida é dissipada como calor. A literatura também distingue eficiência bruta, líquida, delta e de trabalho, cada uma com método de cálculo e uso distintos.

**Ressalva de precisão (2026-08-02):** o trecho-fonte desta nota (Manual de treinamento, p.91) generaliza "no ciclismo" sem diferenciar modalidade. A fonte mais detalhada de nota-0230 (McArdle, p.207-208) especifica que essa faixa de 20-25% vale para **ciclismo estacionário** (sem resistência de arrasto); no **ciclismo de estrada** — a modalidade relevante para este produto — a eficiência mecânica **cai abaixo de 20%**, porque parte da energia é gasta vencendo arrasto aerodinâmico em vez de virar trabalho mecânico útil mensurável. Ao citar essa faixa em qualquer feedback futuro, usar a distinção de nota-0230, não a generalização desta nota.

Aplicação ao feedback: nota de referência conceitual — nenhuma dessas métricas é diretamente calculável a partir de dados do Strava (exigem VO2 medido), mas fundamentam por que dois atletas com a mesma FTP podem ter capacidades de sustentação muito diferentes em provas longas (ligado à durabilidade, ver notas do Livro 1 sobre TTE/Stamina).$m2951$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m2952$nota-0205$m2952$, $m2953$VO2máx como preditor de mortalidade/doença cardiovascular — associação mais forte que fatores de risco tradicionais (colesterol, IMC, glicemia); citação de estudo único (Laukkanen 2022)$m2953$, $m2954$fisiologia$m2954$,
  $m2955$contexto$m2955$, $m2956$conceito$m2956$,
  ARRAY[$m2957$mensal$m2957$]::text[], '{}'::text[],
  0.55, $m2958$ativo$m2958$, $m2959$**Política de ativação aplicada:** a afirmação central (aumentar VO2máx em 3,5 mL/kg/min reduz mortalidade por todas as causas em 11%; top 1/3 de aptidão aeróbia tem 45% menos risco que o 1/3 inferior) é atribuída a um único estudo epidemiológico citado (Laukkanen et al. 2022, Mayo Clinic Proceedings) — downgrade para `aplicacao: contexto` por depender de estudo isolado, sem replicação cruzada dentro do próprio livro. VO2máx é descrito como medida de função integrada do corpo todo (sistema nervoso autônomo, coração/vasos, pulmões, músculos, mitocôndrias), com associação a mortalidade mais forte que fatores de risco cardiovascular tradicionais (colesterol, IMC, glicemia) segundo a fonte.

Aplicação ao feedback: fora do escopo de interpretação de dados de treino do Strava — é conteúdo de motivação/saúde de longo prazo (longevidade), não uma regra de interpretação de sessão. Poderia servir como texto educativo de fundo caso o produto queira comunicar "por que treinar aptidão aeróbia importa", mas não deve ser citado como se fosse consenso robusto (é um único estudo) nem usado para gerar previsões individuais de risco de mortalidade.$m2959$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m2960$nota-0210$m2960$, $m2961$Fatores centrais (pulmão, débito cardíaco máx., capacidade de transporte de O2 do sangue) vs. periféricos (gradiente de difusão, enzimas mitocondriais, densidade capilar) — consenso: débito cardíaco máximo é o principal limitante do VO2máx em exercício de corpo inteiro$m2961$, $m2962$fisiologia$m2962$,
  $m2963$contexto$m2963$, $m2964$conceito$m2964$,
  ARRAY[$m2965$mensal$m2965$]::text[], '{}'::text[],
  0.65, $m2966$ativo$m2966$, $m2967$Detalha os dois grupos de fatores limitantes do VO2máx, já introduzidos pela Equação de Fick (nota-0162): (1) Fatores centrais — capacidade de difusão pulmonar (raramente limitante em pessoas saudáveis não-treinadas; pode limitar atletas de elite com débito cardíaco muito alto, que sofrem dessaturação arterial por o sangue passar rápido demais pelo pulmão — respirar ar hiperóxico não aumenta VO2máx em pessoas normais, mas aumenta ligeiramente em atletas altamente treinados), débito cardíaco máximo (FC×volume sistólico — o principal diferencial individual é o volume sistólico máximo), e capacidade de transporte de O2 do sangue (hemoglobina — pode ser limitante em anemia, intoxicação por monóxido de carbono, altitude); (2) Fatores periféricos — gradiente de difusão periférica (resistência à difusão entre hemácia e membrana muscular), enzimas mitocondriais, e densidade capilar (aumenta com o treino, prolongando o tempo de trânsito do sangue no capilar e permitindo maior extração de O2). Consenso científico: o débito cardíaco máximo é o fator limitante dominante do VO2máx em exercício de corpo inteiro (ex.: ciclismo, corrida); em exercícios com grupos musculares pequenos, esse papel é bem menos importante.

Aplicação ao feedback: nota de fundamentação fisiológica — não gera regra de interpretação direta de dado do Strava, mas reforça por que adaptações cardiovasculares (débito cardíaco) tendem a ser o alvo mais eficiente de treino de VO2máx, mais do que adaptações puramente musculares/periféricas.$m2967$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
COMMIT;