BEGIN;
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m3080$nota-0211$m3080$, $m3081$Dobrar as mitocôndrias não dobra o VO2máx (aumento real de apenas 20-40%) — o principal efeito de mais mitocôndrias é melhorar a performance de endurance (mais oxidação de gordura, menos lactato), não elevar o teto de VO2máx$m3081$, $m3082$fisiologia$m3082$,
  $m3083$contexto$m3083$, $m3084$conceito$m3084$,
  ARRAY[$m3085$mensal$m3085$]::text[], '{}'::text[],
  0.6, $m3086$ativo$m3086$, $m3087$Achado contraintuitivo e bem estabelecido (não é estudo único — é consenso da fisiologia do exercício): embora mais mitocôndrias devessem, em teoria, permitir extrair mais oxigênio (e portanto aumentar o VO2máx proporcionalmente), estudos mostram que dobrar (ou mais) a quantidade de mitocôndrias produz apenas um aumento modesto de 20-40% no VO2máx — consistente com a visão de que o VO2máx é limitado pela entrega de oxigênio (débito cardíaco, nota-0210), não pela capacidade mitocondrial de utilizá-lo. O principal efeito prático de mais mitocôndrias/enzimas oxidativas não é elevar o teto de VO2máx, e sim melhorar a performance de endurance por dois mecanismos: (1) maior oxidação de gordura (poupando glicogênio muscular e glicemia); (2) menor produção de lactato para a mesma intensidade. Isso explica por que a performance de endurance melhora com o treino mesmo sem grande mudança no VO2máx.

Aplicação ao feedback: reforça uma distinção já implícita no cânone (Manual, nota-0165: em atletas avançados o foco desloca de VO2máx para economia/limiares) — treino de base aeróbia (que aumenta densidade mitocondrial) deve ser comunicado ao usuário como melhoria de "eficiência/resistência à fadiga" mais do que como aumento esperado de VO2máx ou FTP de curto prazo; útil para calibrar expectativas de feedback sobre o que diferentes tipos de treino realmente melhoram.$m3087$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m3088$nota-0213$m3088$, $m3089$Metabolismo anaeróbio contribui ~10-20% do ATP total em eventos de 10-30min (ex.: 5-10km corrida); é pequeno em maratona — densidade capilar ajuda a tolerar mais essa produção de lactato$m3089$, $m3090$fisiologia$m3090$,
  $m3091$contexto$m3091$, $m3092$referencia$m3092$,
  ARRAY[$m3093$diario$m3093$]::text[], '{}'::text[],
  0.55, $m3094$ativo$m3094$, $m3095$Em eventos de endurance com duração de 10-30 minutos (ex.: 5-10km de corrida; por extensão, esforços cicláveis de duração equivalente como um CRI curto ou uma subida de 10-20min), o metabolismo anaeróbio contribui aproximadamente 10-20% do turnover total de ATP — contribuição pequena em provas mais longas (maratona) e mais significativa nessa janela intermediária. Maior densidade capilar muscular ajuda a remover/reciclar metabólitos fatigantes (íons H+), aumentando a tolerância à produção de lactato e permitindo sustentar um "Performance VO2" mais alto (nota-0212).

Aplicação ao feedback: fornece uma faixa de referência que pode contextualizar esforços de 10-30min identificados no Strava (ex.: um segmento/CRI dessa duração) — parte relevante da carga fisiológica vem de vias anaeróbias mesmo sendo majoritariamente um esforço "aeróbio", reforçando por que esforços dessa duração são particularmente exigentes e difíceis de recuperar rapidamente.$m3095$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m3096$nota-0214$m3096$, $m3097$Economia de movimento varia 20-30% entre ciclistas (30-40% entre corredores) para a mesma velocidade/potência; fibras tipo I são mecanicamente mais eficientes que tipo II, mas a correlação fibra-economia não é forte$m3097$, $m3098$fisiologia$m3098$,
  $m3099$contexto$m3099$, $m3100$referencia$m3100$,
  ARRAY[$m3101$mensal$m3101$]::text[], '{}'::text[],
  0.55, $m3102$ativo$m3102$, $m3103$O custo de oxigênio para produzir a mesma potência varia cerca de 20-30% entre ciclistas (30-40% entre corredores para a mesma velocidade) — uma diferença individual considerável, mesmo controlando pela intensidade. Fibras musculares tipo I (contração lenta) são mecanicamente mais eficientes que fibras tipo II (contração rápida); ciclistas de endurance de elite tendem a ter maior proporção de fibras tipo I, contribuindo para melhor economia. Entretanto, a correlação entre composição de fibras e economia não é forte — treino intervalado intenso aumenta a atividade mitocondrial tanto em fibras tipo I quanto tipo II, indicando que a eficiência não depende só do tipo de fibra.

Aplicação ao feedback: fundamenta por que dois ciclistas com a mesma FTP podem ter capacidades de sustentação muito diferentes (diferença de até ~20-30% no custo metabólico da mesma potência) — reforça a cautela de não comparar diretamente atletas apenas por FTP/potência absoluta sem considerar essa variação individual de economia (complementa a nota-0179 e a lógica de perfil fenotípico já no cânone).$m3103$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m3104$nota-0215$m3104$, $m3105$Eficiência mecânica no ciclismo É treinável ao longo de anos (~8% de melhora observada) — contradiz a crença antiga de que era praticamente fixa$m3105$, $m3106$fisiologia$m3106$,
  $m3107$contexto$m3107$, $m3108$conceito$m3108$,
  ARRAY[$m3109$mensal$m3109$]::text[], '{}'::text[],
  0.55, $m3110$ativo$m3110$, $m3111$Contraria a crença científica anterior de que a eficiência de pedalada/economia de corrida seriam praticamente fixas e pouco responsivas ao treino. Evidência mais recente mostra que a eficiência mecânica no ciclismo pode melhorar aproximadamente 8% ao longo de vários anos de treinamento consistente (mesmo em atletas de elite já treinados), enquanto a economia de corrida melhora entre 8-14% ao longo de anos. Os mecanismos exatos não são totalmente compreendidos, mas podem envolver mudanças na composição de isoformas das fibras musculares e outras adaptações de longo prazo do treino de endurance.

Aplicação ao feedback: reforça, com evidência adicional, que ganhos de eficiência/economia são um processo de anos (não semanas) — relevante para calibrar expectativas de progresso no feedback de longo prazo: se a FTP/potência não sobe rapidamente mas o atleta treina consistentemente há anos, parte do ganho de desempenho pode estar vindo de melhoria de eficiência (não capturada diretamente por FTP), consistente com a lógica de "economia se degrada com fadiga, mas melhora com treino consistente" já registrada na nota-0179/nota-0180.$m3111$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
COMMIT;