BEGIN;
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m11399$nota-0246$m11399$, $m11400$Razão trabalho:recuperação recomendada varia por sistema energético alvo — 1:3 para fosfagênio (ATP-PCr), 1:2 para glicolítico, 1:1 a 1:1,5 para aeróbio de longa duração$m11400$, $m11401$tipos-de-treino$m11401$,
  $m11402$contexto$m11402$, $m11403$protocolo$m11403$,
  ARRAY[$m11404$diario$m11404$]::text[], '{}'::text[],
  0.65, $m11405$revisar$m11405$, $m11406$McArdle formaliza a prescrição de treino intervalado com base em quatro variáveis (intensidade do intervalo de esforço, duração do intervalo de esforço, duração do intervalo de recuperação, número de repetições) e recomenda razões trabalho:recuperação distintas conforme o sistema energético que se deseja sobrecarregar:

- **Sistema fosfagênio (ATP-PCr, esforços "alácticos" de até ~10s, ex.: sprints curtos):** razão de recuperação **1:3**. Exemplo do texto: intervalos de corrida de 10s → recuperação de ~30s (3×10s). Pouco lactato se acumula; a recuperação é rápida, permitindo reiniciar o esforço logo após um breve descanso.
- **Sistema glicolítico de curto prazo (esforços de ~1min com acúmulo relevante de lactato):** razão de recuperação **1:2** (recuperação em média o dobro da duração do esforço). Essa razão garante restauração suficiente de fosfatos intramusculares e/ou remoção de lactato suficiente para que o próximo esforço prossiga com fadiga mínima.
- **Sistema aeróbio de longa duração (intervalos de alta intensidade de 60-90s):** razão de recuperação **1:1 a 1:1,5**. Nesse caso, o consumo de oxigênio sobe rapidamente mas permanece insuficiente para suprir a demanda energética; a recuperação recomendada é deliberadamente incompleta (o intervalo seguinte começa antes do retorno ao consumo de oxigênio basal), garantindo que o estresse cardiovascular e metabólico atinja níveis próximos do pico repetidamente. A duração exata do intervalo de recuperação importa menos em intervalos mais longos, pois há tempo suficiente para o corpo ajustar parâmetros metabólicos e circulatórios durante a própria atividade.

Contraste importante: quanto mais curto e mais dependente do sistema fosfagênio/glicolítico o intervalo, maior a razão de recuperação necessária (1:2 a 1:3); quanto mais longo e dependente do sistema aeróbio, menor a razão necessária (~1:1), podendo até ser deliberadamente incompleta.

Aplicação ao feedback: nota de contexto — os números originais do livro são calibrados para corrida/natação em distâncias (jardas) e não têm tradução direta em potência de ciclismo sem adaptação; o produto não deve aplicar as razões literalmente a partir de um sinal isolado do Strava. Serve como referência ao avaliar se a estrutura de um treino intervalado registrado (via potência-série-temporal e potência-por-lap) é coerente com o sistema energético que o atleta provavelmente pretendia treinar — ex.: um treino de "sprints" com razão de recuperação muito menor que 1:2 pode não permitir restauração adequada do sistema glicolítico entre repetições, e um treino de "VO2máx" com razão de recuperação muito maior que ~1:1 pode não acumular estresse cardiovascular suficiente.$m11406$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
INSERT INTO notas (id, titulo, dominio_slug, aplicacao_slug, tipo_nota_slug, camadas, sinais, confianca, status, corpo) VALUES (
  $m11407$nota-0248$m11407$, $m11408$Tabela ACSM de prescrição de treino de força por objetivo (força máxima, hipertrofia, potência, resistência muscular) e nível de treino (novato/intermediário/avançado): séries, repetições, %1RM e descanso$m11408$, $m11409$tipos-de-treino$m11409$,
  $m11410$contexto$m11410$, $m11411$protocolo$m11411$,
  ARRAY[$m11412$semanal$m11412$]::text[], '{}'::text[],
  0.65, $m11413$revisar$m11413$, $m11414$O posicionamento oficial do American College of Sports Medicine (ACSM, 2002) resumido por McArdle (Tabela 22.2) prescreve variáveis de treino de força distintas conforme o **objetivo** (força máxima, hipertrofia, potência, resistência muscular) e o **nível de treino** (novato/intermediário/avançado). Parâmetros principais por objetivo (valores aproximados, variando por nível):

- **Força máxima:** 60-70% de 1RM (novato) a carga periodizada de 1RM (avançado); 1-3 séries de 8-12 repetições (novato) evoluindo para séries múltiplas de 1-12 repetições (avançado); descanso de 2-3 min entre séries; frequência de 2-3x/semana (novato) a 4-6x/semana (avançado). Regra geral citada: 8-12RM é eficaz para novatos, 1-12RM para intermediários, evoluindo a cargas mais intensas de 1-6RM.
- **Hipertrofia:** cargas semelhantes à força (60-100% de 1RM conforme nível), mas com ênfase em 6-12 repetições e descanso mais curto (1-2 min, exceto séries muito pesadas).
- **Potência:** combina duas faixas de carga — cargas pesadas (>80% de 1RM) para desenvolver força de base, e cargas leves (30-60% de 1RM) executadas com velocidade de contração rápida para desenvolver velocidade; séries de 1-6 repetições em níveis avançados, com ênfase em exercícios multiarticulares.
- **Resistência muscular:** cargas mais leves, 50-70% de 1RM (novato) a 30-80% de 1RM periodizado (avançado); séries de 10-15 repetições (novato) a 10-25+ repetições (avançado); descanso mais curto (<1 min para séries de 10-15 reps em intermediários).

Princípios gerais de progressão citados: aumentar a carga em 2-10% quando o indivíduo consegue completar 1-2 repetições acima do número-alvo; sequenciar exercícios de grupos musculares grandes antes de pequenos, multiarticulares antes de uniarticulares; treino em dias alternados (2x a cada 2 dias) supera treino diário para o mesmo grupo muscular; velocidade de movimento mais rápida gera maior ganho de força que movimento lento (mas hipertrofia com foco em fibras rápidas ocorre principalmente com treino em velocidade rápida).

Aplicação ao feedback: fora do escopo direto de dados do Strava (o app não registra carga/RM/séries de treino de força), mas serve como referência técnica caso o produto amplie o feedback para sessões de força registradas como atividades separadas (ex.: "Weight Training" no Strava) — útil para verificar se os parâmetros relatados pelo atleta (quando disponíveis via input manual) correspondem ao objetivo declarado (ex.: um ciclista buscando potência/sprint mas treinando exclusivamente em 10-15 reps a 50-70% 1RM está mais alinhado ao protocolo de resistência muscular do que ao de potência).$m11414$
)
ON CONFLICT (id) DO UPDATE SET titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, aplicacao_slug=excluded.aplicacao_slug, tipo_nota_slug=excluded.tipo_nota_slug, camadas=excluded.camadas, sinais=excluded.sinais, confianca=excluded.confianca, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
COMMIT;