BEGIN;
INSERT INTO skills (id, numero, titulo, dominio_slug, tipo_skill_slug, notas_usadas, confianca_herdada, condicao_nao_calculavel, dados_necessarios, skills_relacionadas, log_de_teste, status, corpo) VALUES (
  $m34283$skill-gerais-fadiga-carga-avancada$m34283$, $m34284$skill-0013$m34284$, $m34285$Fadiga e carga avançada — estagnação por platô de CTL, TSB-alvo por evento, overreached vs. OTS, potência vs. FC, concordância de sinais, dias de recuperação por TSS$m34285$,
  $m34286$recuperacao-e-fadiga$m34286$, $m34287$detector$m34287$,
  ARRAY[$m34288$nota-0089$m34288$, $m34289$nota-0091$m34289$, $m34290$nota-0116$m34290$, $m34291$nota-0148$m34291$, $m34292$nota-0001$m34292$, $m34293$nota-0158$m34293$, $m34294$nota-0185$m34294$, $m34295$nota-0194$m34295$, $m34296$nota-0198$m34296$, $m34297$nota-0063$m34297$, $m34298$nota-0086$m34298$]::text[],
  $m34299$0.55$m34299$, $m34300$sem série de CTL/ATL/TSB (pré-requisito: skill-gerais-pmc) → os passos que dependem de TSB (TSB-alvo por evento, priorização em ultraresistência, distinção overreached/OTS) ficam Ausentes. Sem FC disponível na atividade → os passos que cruzam potência×FC (decoupling, fatores de confusão, carga externa vs. interna) ficam Ausentes para esse eixo, mas o eixo baseado só em TSS/potência permanece calculável. Regra inegociável da nota-0198: se só houver 1 sinal disponível (ex.: só TSS, sem FC nem esforço-relativo), a skill NUNCA deve disparar o alerta de 'fadiga acumulada/risco de overreaching' — reportar como indeterminado, não como 'sem fadiga' nem como 'fadigado'. Sem idade do atleta declarada → o passo 4b (checagem de constante de ATL por idade, nota-0086) não é aplicável; assumir silenciosamente que a constante de 7 dias usada por skill-gerais-pmc é adequada, sem emitir alerta de possível desajuste.$m34300$,
  $m34301$[{"campo": "serie_ctl_atl_tsb", "tipo": "calculado", "obrigatorio": "true", "fonte": "skill-gerais-pmc"}, {"campo": "fc_serie_temporal", "tipo": "bruto", "obrigatorio": "false", "fonte": "sensor de FC", "observacao": "sem isso, eixo potência×FC (decoupling) fica Ausente, mas o eixo TSS/potência permanece calculável"}, {"campo": "esforco_relativo_rpe", "tipo": "bruto", "obrigatorio": "false", "fonte": "Strava: perceived exertion / esforço relativo da atividade", "observacao": "um dos sinais da regra de concordância de ≥2 sinais"}, {"campo": "tipo_evento_declarado", "tipo": "manual", "obrigatorio": "false", "fonte": "declaração do atleta sobre duração/natureza do evento-alvo", "observacao": "usado no TSB-alvo por tipo de evento"}, {"campo": "idade_atleta", "tipo": "manual", "obrigatorio": "false", "fonte": "perfil do atleta", "observacao": "usada só para a checagem de consistência da constante de ATL (nota-0086, passo 4b) — não recalcula o ATL, que é responsabilidade de skill-gerais-pmc"}, {"campo": "constante_tempo_atl_usada_dias", "tipo": "calculado", "obrigatorio": "false", "fonte": "skill-gerais-pmc (parâmetro usado no cálculo do ATL, tipicamente 7 dias)", "observacao": "sem esse dado, não é possível comparar contra a faixa recomendada por idade (nota-0086) e o passo 4b fica Ausente"}]$m34301$::jsonb, $m34302$[{"id": "skill-gerais-pmc", "tipo": "pre-requisito"}, {"id": "skill-gerais-tss-sessao", "tipo": "pre-requisito"}, {"id": "skill-gerais-ambiente-termico", "tipo": "complementar"}, {"id": "skill-classificacao-semana-recuperacao", "tipo": "complementar"}]$m34302$::jsonb,
  $m34303$[{"data": "2026-08-01", "caso": "Atividade real 19556658969 (Voturuna-Itu, 97,5km/4h02, TSS=266,40) — ver analises/analise-2026-08-01-19556658969.md", "resultado": "Eixo potência×FC (decoupling) calculado com dado real: 1ª metade P=180,6W/FC=150,1bpm (razão 1,204), 2ª metade P=147,1W/FC=142,7bpm (razão 1,031) — queda de 14,3% na razão P:FC, reportado como sinal clássico de fadiga acumulada (nota-0001), não como sessão ficando mais fácil. Eixo TSS→dias de recuperação (Tabela 7.3, nota-0063) aplicado corretamente: TSS 266,4 caiu na faixa 150-300 → fadiga residual possível até o 2º dia. Eixos dependentes de TSB (TSB-alvo por evento, distinção overreached/OTS, regra de concordância de ≥2 sinais do passo 9) ficaram corretamente Ausentes — sem série de CTL/ATL/TSB de 90 dias disponível nesta sessão (pré-requisito de skill-gerais-pmc não satisfeito no momento da análise).", "veredito": "Validação PARCIAL com dado real — os dois eixos calculáveis sem TSB (decoupling potência×FC via nota-0001; Tabela 7.3 via nota-0063) produziram leituras corretas e rastreáveis, sem falso positivo de fadiga (não disparou alerta forte com só 1-2 sinais parciais, consistente com a regra de concordância). Os eixos que dependem de TSB (a maior parte da skill: TSB-alvo por evento, overreached vs. OTS, threshold de TSB muito negativo do passo 9) permanecem sem validação com dado real — precisam de um caso com série de CTL/ATL/TSB de 90 dias disponível (ex.: reaproveitar a série já validada de skill-gerais-pmc, caso Serra Negra) para fechar a validação completa. status mantido 'proposto', não promovido a 'validado_com_ressalvas', até essa segunda rodada."}]$m34303$::jsonb, $m34304$proposto$m34304$, $m34305$## O que faz

Aplica um conjunto de regras avançadas de interpretação de fadiga e carga, além do cálculo básico de CTL/ATL/TSB (feito por `skill-gerais-pmc`): detecta estagnação de treino por platô prolongado de CTL, ajusta o TSB-alvo pré-prova pelo tipo/duração do evento, prioriza TSB sobre picos de potência recente em provas de ultraresistência, distingue overreaching agudo de overtraining crônico pela duração da recuperação, aplica a regra de que potência é mais confiável que FC para detectar fadiga (mas com cautela sobre confundidores da FC), trata potência/FC/RPE como sinais complementares nunca substituíveis entre si, nunca afirma "fadigado" só com TSS alto, exige concordância de pelo menos 2 sinais antes de alertar fadiga acumulada, e estima dias de recuperação esperados de uma sessão via a Tabela 7.3.

## Quando usar

- Ao avaliar se um período de treino consistente na verdade estagnou (CTL platôs).
- Ao aproximar-se de uma prova e decidir a estratégia de taper/TSB-alvo.
- Ao interpretar decoupling de FC (mais baixa ou mais alta que o habitual) numa sessão.
- Ao decidir se um estado de fadiga observado é um alerta sério (OTS) ou normal (overreaching agudo recuperável).
- Sempre que for gerar um alerta de "fadiga acumulada" ou "risco de overtraining" — esta skill define o critério de quando esse alerta pode disparar.

## Passo a passo

1. **Detectar estagnação**: se o CTL ficou estável por 4-6 semanas sem mudança de foco de treino e sem evolução de performance correspondente, sinalizar possível estagnação e sugerir progressão de carga em vez de repetir o padrão atual (nota-0089).
2. **TSB-alvo pré-prova por tipo de evento** (tratar como heurística, não limiar rígido — nota-0091 é "revisar"): para eventos curtos/muito anaeróbios (pista, BMX, subidas curtas), recomendar taper para TSB bem positivo (bem descansado); para eventos longos/aeróbios, alertar contra descanso excessivo — TSB pode ficar neutro ou levemente negativo sem prejudicar a performance, e tapear demais arrisca perder a janela de pico de forma.
3. **Ultraresistência (>3-4h)** (heurística — nota-0116 é "revisar"): priorizar TSB (valor e trajetória) no dia da prova sobre picos recentes de MMP como indicador de prontidão. Não usar "melhor 20min da temporada" como proxy de prontidão para esse tipo de prova.
4. **Classificar severidade de um estado de fadiga**: se a performance se recupera em poucos dias após reduzir a carga, classificar como overreaching agudo (não é motivo de alarme excessivo); se a queda de desempenho persiste por mais de 30 dias mesmo com descanso, sinalizar indício de Overtraining Syndrome (OTS) real — recomendação de resposta muito mais séria, incluindo considerar acompanhamento médico (nota-0148).
4b. **Checar consistência da constante de tempo do ATL por idade** (nota-0086): se a idade do atleta e a constante de tempo usada no cálculo do ATL (`skill-gerais-pmc`) estiverem disponíveis, comparar contra a Tabela 9.1 — <19 anos: 2-4 dias; 20-29: 4-7 dias; 30-49: 6-8 dias; 50-59: 7-10 dias; 60-65: 9-12 dias; 66-70+: 11-14 dias. Se a constante usada estiver claramente fora da faixa recomendada para a idade do atleta (ex.: 7 dias padrão para um atleta de 65 anos, quando a faixa recomendada é 9-12), sinalizar que a classificação de fadiga desta skill (overreached/OTS, TSB-alvo) pode estar distorcida — um atleta mais velho com constante subdimensionada pode ter sua recuperação mais lenta (normal para a idade) mal-interpretada como fadiga anômala; um atleta mais jovem com constante superdimensionada pode ter alertas de fadiga atrasados. Esta skill não recalcula o ATL — apenas sinaliza o desajuste para reforçar cautela na leitura dos passos anteriores.
5. **Decoupling Pw:Hr**: se a FC está mais baixa que o habitual para uma dada potência, NÃO interpretar como "sessão fácil" — é mais provável fadiga acumulada de dias anteriores; usar a potência (não a FC) para orientar a necessidade de descanso, cruzando com a carga recente (TSS/CTL/ATL) (nota-0001).
6. **Fatores de confusão da FC**: antes de sinalizar decoupling ou fadiga cardiovascular só por FC elevada/reduzida isolada, considerar temperatura, hidratação, altitude, estresse psicológico e cafeína — cruzar com `skill-gerais-ambiente-termico` quando o contexto for relevante (nota-0158).
7. **Carga externa vs. interna**: tratar potência (carga externa), FC (parte da carga interna) e esforço-relativo/RPE do Strava (resposta global) como sinais complementares — cruzar as três antes de concluir se uma sessão foi "fácil na potência mas fisiologicamente cara" (nota-0185).
8. **TSS não é fadiga real**: nunca afirmar "atleta fadigado" só porque o TSS acumulado está alto — TSS mede carga mecânica externa, não o estado fisiológico real. Cruzar sempre com pelo menos um sinal de carga interna disponível (nota-0194).
9. **Regra de concordância de ≥2 sinais**: antes de disparar qualquer alerta de "fadiga acumulada" ou "risco de overreaching", exigir que pelo menos 2 dos sinais disponíveis (potência reduzida sustentável, decoupling Pw:Hr elevado, TSB muito negativo, esforço-relativo desproporcionalmente alto) estejam concordando. Um único sinal isolado nunca é suficiente (nota-0198). **"TSB muito negativo" não tem corte numérico no cânone** — usar a definição relativa ao histórico do próprio atleta descrita em `fallback_tsb_muito_negativo` (frontmatter); sem linha de base de 90 dias disponível, tratar este sinal específico como indeterminado (não contar a favor nem contra a concordância).
10. **Dias de recuperação esperados por sessão**: usar a Tabela 7.3 para estimar o impacto de uma sessão específica — TSS<150: baixo, recuperação completa no dia seguinte; 150-300: moderado, fadiga residual possível até o 2º dia; 300-450: alto, fadiga residual mesmo após 2 dias; >450: muito alto, fadiga residual por vários dias (nota-0063).
11. **Checar a condição de não-calculável** (ver frontmatter) antes de reportar qualquer alerta — em especial a regra inegociável dos ≥2 sinais do passo 9.

## Output

```
{
  "estagnacao_ctl": {"detectada": <bool, null>, "semanas_platô": <float, null>},
  "tsb_alvo_pre_prova": {"tipo_evento": "curto_anaerobio" | "longo_aerobio" | null, "tsb_atual": <float, null>, "dentro_da_faixa_recomendada": <bool, null>},
  "prioridade_ultraresistencia": <bool>,
  "classificacao_fadiga": "overreached_agudo" | "overtraining_syndrome_suspeito" | "indeterminado" | null,
  "constante_atl_consistente_com_idade": {"consistente": <bool, null>, "constante_usada_dias": <float, null>, "faixa_recomendada_dias": "<texto, ex.: '9-12'>"},
  "decoupling": {"fc_abaixo_do_habitual": <bool, null>, "leitura": "provavel_fadiga_nao_facilidade" | null, "fatores_confusao_considerados": ["<texto>"]},
  "sinais_concordantes": {"potencia_reduzida": <bool>, "decoupling_elevado": <bool>, "tsb_muito_negativo": <bool, null se linha de base de 90 dias indisponível>, "esforco_relativo_alto": <bool>, "total_concordantes": <int>},
  "alerta_fadiga_acumulada": <bool>,
  "dias_recuperacao_esperados": "menos_1_dia" | "1_2_dias" | "mais_2_dias" | "varios_dias" | null,
  "alertas": [
    "estagnacao_ctl" | "tsb_fora_da_faixa_recomendada" | "overtraining_syndrome_suspeito" | "fadiga_acumulada_concordante" | "sinal_isolado_insuficiente_nao_alertar" | "constante_atl_desajustada_para_idade" | null
  ],
  "provenance": "Medido" | "Estimado" | "Ausente",
  "motivo_provenance": "<texto, obrigatório se Estimado ou Ausente>",
  "notas_citadas": ["nota-0089", "nota-0091", "nota-0116", "nota-0148", "nota-0001", "nota-0158", "nota-0185", "nota-0194", "nota-0198", "nota-0063", "nota-0086"]
}
```$m34305$
)
ON CONFLICT (id) DO UPDATE SET numero=excluded.numero, titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, tipo_skill_slug=excluded.tipo_skill_slug, notas_usadas=excluded.notas_usadas, confianca_herdada=excluded.confianca_herdada, condicao_nao_calculavel=excluded.condicao_nao_calculavel, dados_necessarios=excluded.dados_necessarios, skills_relacionadas=excluded.skills_relacionadas, log_de_teste=excluded.log_de_teste, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
COMMIT;