BEGIN;
INSERT INTO skills (id, numero, titulo, dominio_slug, tipo_skill_slug, notas_usadas, confianca_herdada, condicao_nao_calculavel, dados_necessarios, skills_relacionadas, log_de_teste, status, corpo) VALUES (
  $m34158$skill-gerais-ambiente-termico$m34158$, $m34159$skill-0011$m34159$, $m34160$Ambiente térmico — aclimatização ao calor, imunossupressão pós-esforço, desidratação, degradação de desempenho e hipotermia$m34160$,
  $m34161$fisiologia$m34161$, $m34162$calculadora+detector$m34162$,
  ARRAY[$m34163$nota-0254$m34163$, $m34164$nota-0242$m34164$, $m34165$nota-0256$m34165$, $m34166$nota-0257$m34166$, $m34167$nota-0258$m34167$, $m34168$nota-0261$m34168$, $m34169$nota-0270$m34169$, $m34170$nota-0251$m34170$, $m34171$nota-0252$m34171$, $m34172$nota-0253$m34172$, $m34173$nota-0266$m34173$, $m34174$nota-0267$m34174$]::text[],
  $m34175$0.55$m34175$, $m34176$sem dado de temperatura na atividade (Strava nem sempre captura) → nenhum detector desta skill é aplicável, reportar Ausente. Sem histórico de atividades anteriores do atleta → aclimatização ao calor não é inferível. Sem dado de velocidade/potência (para inferir vento relativo do próprio deslocamento) → o ajuste de wind-chill por velocidade do ciclista (nota-0266) não é aplicável, usar só a temperatura do ar como proxy conservador. NENHUM destes detectores substitui avaliação clínica real — são alertas educativos baseados em proxy indireto (temperatura + duração + FC + velocidade do Strava), nunca um diagnóstico; a skill nunca deve afirmar que o atleta 'está' em exaustão por calor, golpe de calor ou um estágio específico de hipotermia, só sinalizar risco crescente no continuum e, no caso de hipotermia, citar a tabela de estágios (nota-0267) como referência educativa de gravidade, não como diagnóstico do atleta.$m34176$,
  $m34177$[{"campo": "temperatura_atividade", "tipo": "bruto", "obrigatorio": "true", "fonte": "Strava: temperatura registrada na atividade", "observacao": "nem sempre disponível — sem isso, nenhum detector é aplicável"}, {"campo": "fc_serie_temporal", "tipo": "bruto", "obrigatorio": "false", "fonte": "sensor de FC, para o cálculo de decoupling por desidratação"}, {"campo": "historico_exposicao_calor", "tipo": "bruto", "obrigatorio": "false", "fonte": "temperatura das atividades dos últimos 10-14 dias, para inferir aclimatização"}, {"campo": "velocidade_serie_temporal", "tipo": "bruto", "obrigatorio": "false", "fonte": "stream de velocidade/GPS, para o ajuste de vento relativo (nota-0266) no alerta de hipotermia", "observacao": "sem isso, usar só a temperatura do ar como proxy conservador de risco de frio"}, {"campo": "peso_corporal_kg", "tipo": "manual", "obrigatorio": "false", "fonte": "perfil do atleta", "observacao": "necessário para converter litros de suor estimados (nota-0256) em % de massa corporal e aplicar a estimativa de impacto em VO2máx/resistência (nota-0257); sem isso, o passo 3 reporta só o decoupling de FC/débito cardíaco, sem a estimativa de VO2máx/resistência"}]$m34177$::jsonb, $m34178$[{"id": "skill-gerais-fadiga-carga-avancada", "tipo": "complementar"}]$m34178$::jsonb,
  $m34179$[]$m34179$::jsonb, $m34180$proposto$m34180$, $m34181$## O que faz

Infere o estado de aclimatização ao calor do atleta a partir do histórico recente de exposição, e aplica cinco detectores de segurança/interpretação térmica: janela de imunossupressão após esforço excepcional, efeito da desidratação sobre FC/débito cardíaco (mecanismo de decoupling em sessões quentes), degradação progressiva de desempenho com o calor, continuum de doença por calor (cãibras→exaustão→golpe de calor), e risco de hipotermia por roupa molhada.

## Quando usar

- Ao interpretar FC elevada ou decoupling numa sessão longa em dia quente — antes de concluir "perda de fitness" ou "sessão difícil".
- Ao gerar feedback logo após uma sessão de TSS/esforço muito acima do padrão do atleta (prova longa, evento excepcional).
- Ao comparar desempenho do mesmo atleta entre sessões em temperaturas diferentes.
- Ao identificar combinação de frio + chuva/suor + queda de intensidade (ex.: início de descida) que eleve risco de hipotermia.

## Passo a passo

1. **Inferir aclimatização ao calor:** se o atleta teve exposição repetida a temperatura elevada ao longo de ~10-14 dias recentes, considerar total/parcialmente aclimatizado (maior ganho na 1ª semana, plena em ~10 dias). Se sem exposição a calor nas últimas 2-3 semanas, tratar como não aclimatizado e reforçar avisos de hidratação/ritmo conservador na próxima sessão quente (nota-0254).
2. **Sinalizar janela de imunossupressão** se uma sessão teve TSS/esforço-relativo muito acima do padrão do atleta (evento isolado excepcional, não acúmulo crônico): alertar que as próximas 3-72h são de maior vulnerabilidade a infecção respiratória, com efeito residual até 1-2 semanas — tratar com cautela extra por ser nota "revisar" (nota-0242).
3. **Ao detectar decoupling elevado** numa sessão longa (>1,5-2h) e quente: cruzar com temperatura e duração para estimar se desidratação é causa provável. Regra grosseira de ordem de grandeza: subida de FC de ~8bpm ao longo da sessão é compatível com ~1L de perda de suor, com queda associada de ~1L/min no débito cardíaco (nota-0256). **Se `peso_corporal_kg` estiver disponível**, converter os litros estimados de suor em % de massa corporal (litros × 1kg/L ÷ peso_corporal_kg × 100) e, só como estimativa educativa de ordem de grandeza (nunca como número preciso), aplicar as razões médias derivadas dos 2 pontos de dado de nota-0257: queda_vo2max_pct ≈ desidratacao_pct × 5,2; queda_resistencia_pct ≈ desidratacao_pct × 11,4 — usar isso para explicar ao atleta por que uma queda de potência/pace desproporcional à duração/intensidade planejada, numa sessão longa e quente, é provavelmente explicada por desidratação, não perda de fitness ou fadiga muscular. Nunca extrapolar essa razão fora do intervalo ~2-4,5% de desidratação (único intervalo com dado de apoio em nota-0257) nem apresentar como valor medido — é sempre `Estimado`.
4. **Ao comparar desempenho do mesmo atleta entre sessões**, esperar degradação progressiva e gradual (não um corte abrupto) conforme a temperatura sobe de ~10°C a 25°C+ — mais acentuada em atletas menos condicionados. Não sinalizar isso como "underperformando" (nota-0258).
5. **Emitir alerta educativo de risco por calor** quando houver combinação de temperatura alta + tempo-movimento prolongado + FC elevada sustentada, especialmente em atleta não aclimatado (passo 1): recomendar reduzir intensidade e buscar hidratação/sombra diante de qualquer mal-estar — nunca afirmar diagnóstico específico (cãibra/exaustão/golpe de calor), só sinalizar risco crescente no continuum (nota-0261). **Classificação de risco por WBGT estimado** (nota-0251, nota-0252): como o Strava só fornece temperatura do ar (não umidade nem carga radiante, os outros dois componentes do WBGT), aplicar os mesmos limiares em °C da tabela ACSM como aproximação conservadora e explicitamente rotulada como estimativa — abaixo de 18°C: risco baixo; 18-23°C: risco moderado; 23-28°C: risco alto (indivíduos sensíveis ao calor não deveriam competir/forçar); acima de 28°C: risco muito alto (considerar adiar sessão-chave). Como o WBGT real tende a ser igual ou maior que a temperatura do ar em dias úmidos/ensolarados (nunca menor), tratar esta classificação como piso do risco real, nunca como teto — reforçar com o texto educativo de nota-0253 (mesma temperatura pode ter risco real bem diferente conforme a umidade, não capturada pelo Strava).
6. **Emitir alerta de risco de hipotermia** quando houver temperatura baixa-moderada (<15°C) + esforço intenso prolongado (sudorese esperada) + queda de potência/velocidade (ex.: início de descida ou parada): recomendar troca de camada ou vestimenta impermeável/corta-vento antes de descidas longas, mesmo sem temperatura extrema (nota-0270). **Ajuste por vento relativo do próprio deslocamento** (nota-0266): quando houver dado de velocidade, considerar que o deslocamento do ciclista já soma vento relativo ao vento ambiente (ex.: pedalar a 30km/h em dia calmo já produz sensação de vento de ~30km/h) — isso amplifica a sensação de frio real além do que a temperatura do ar isolada sugere, especialmente em descidas rápidas logo após subidas suadas (roupa molhada, nota-0270); tratar velocidades sustentadas altas (ex. descidas >30km/h) combinadas com temperatura <15°C como fator agravante adicional, mesmo sem dado de vento ambiente. **Referência educativa de gravidade** (nota-0267): se o alerta de hipotermia for emitido, pode-se citar a tabela de estágios (tremor máximo ~35°C central, tremor cessa ~31°C perdendo a defesa ativa contra frio, risco grave a partir de ~28°C) como conteúdo educativo de por que o risco é sério — nunca como diagnóstico do estágio real do atleta, que não é mensurável pelos dados disponíveis.
7. **Checar a condição de não-calculável** (ver frontmatter) antes de reportar qualquer alerta.

## Output

```
{
  "aclimatizacao_calor": "total" | "parcial" | "nao_aclimatizado" | "nao_inferivel",
  "risco_calor_wbgt_estimado": "baixo" | "moderado" | "alto" | "muito_alto" | null,
  "vento_relativo_amplificado_pela_velocidade": <bool, null>,
  "alertas": [
    "janela_imunossupressao_3_72h" | "decoupling_por_desidratacao_provavel" | "degradacao_esperada_pelo_calor_nao_e_underperforming" | "risco_continuum_calor" | "risco_calor_wbgt_alto_ou_muito_alto_estimado" | "risco_hipotermia_roupa_molhada" | "risco_hipotermia_amplificado_por_velocidade" | null
  ],
  "detalhe_decoupling_desidratacao": "<texto, ex.: 'subida de ~9bpm ao longo de 2h a 28°C — compatível com ~1L de desidratação'>",
  "desidratacao_pct_massa_corporal_estimada": <float, null>,
  "queda_estimada_vo2max_pct": <float, null>,
  "queda_estimada_resistencia_pct": <float, null>,
  "provenance": "Estimado" | "Ausente",
  "motivo_provenance": "<texto, obrigatório — estes são sempre proxies indiretos, nunca medição direta>",
  "notas_citadas": ["nota-0254", "nota-0242", "nota-0256", "nota-0257", "nota-0258", "nota-0261", "nota-0270", "nota-0251", "nota-0252", "nota-0253", "nota-0266", "nota-0267"]
}
```$m34181$
)
ON CONFLICT (id) DO UPDATE SET numero=excluded.numero, titulo=excluded.titulo, dominio_slug=excluded.dominio_slug, tipo_skill_slug=excluded.tipo_skill_slug, notas_usadas=excluded.notas_usadas, confianca_herdada=excluded.confianca_herdada, condicao_nao_calculavel=excluded.condicao_nao_calculavel, dados_necessarios=excluded.dados_necessarios, skills_relacionadas=excluded.skills_relacionadas, log_de_teste=excluded.log_de_teste, status=excluded.status, corpo=excluded.corpo, atualizado_em=now();
COMMIT;